import Link from "next/link";
import { ownedAshaCase } from "@/lib/asha/access";
import { prisma } from "@/lib/prisma";
import { evaluateEligibility } from "@/lib/matching";
import { DocumentType } from "@/generated/prisma/enums";
import { AshaForm } from "@/components/asha/AshaForm";
import { VillagerForm } from "@/components/asha/VillagerForm";
import { chooseAshaSchemeAction, downloadAshaDocumentAction, saveAshaFollowUpAction, submitAshaCaseAction, uploadAshaDocumentAction } from "../actions";

export default async function AshaCasePage({ params }: { params: Promise<{ caseId: string }> }) {
  const { caseId } = await params;
  const { record } = await ownedAshaCase(caseId);
  const app = record.application;
  const draft = app.status === "DRAFT";
  const schemes = draft ? (await prisma.loanScheme.findMany({ where: { isActive: true }, orderBy: { name: "asc" } })).filter(scheme => evaluateEligibility(app, scheme).status === "ELIGIBLE") : [];
  const history = await prisma.applicationStatusEvent.findMany({ where: { applicationId: app.id }, orderBy: { createdAt: "desc" }, take: 20 });
  const date = (value: Date) => value.toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata" });
  return <div className="space-y-6">
    <Link href="/asha-worker" className="text-sm underline">Back to my villagers</Link>
    <header><h1 className="text-3xl font-bold">{record.applicant.name}</h1><p className="mt-2">{record.village} · {app.status.replaceAll("_", " ")}</p><p className="text-sm text-slate-600">{record.phone ? <a href={`tel:${record.phone}`}>{record.phone}</a> : "No phone available"}{record.contactKind === "FAMILY" && ` · Family contact: ${record.contactName}`}</p><p className="mt-2 text-xs text-slate-500">Assistance permission recorded on {date(record.consentedAt)}</p></header>
    <details className="panel"><summary className="cursor-pointer font-bold">1. Villager details {draft ? "· Edit draft" : "· Submitted"}</summary><div className="mt-5">{draft ? <VillagerForm caseId={caseId} values={{ name: record.applicant.name ?? "", village: record.village, phone: record.phone, contactKind: record.contactKind, contactName: record.contactName, projectCategory: app.projectCategory, trade: app.trade, gender: app.gender, age: app.age, annualIncome: app.annualIncome?.toString(), requestedAmount: app.requestedAmount?.toString(), applicantTags: app.applicantTags }} /> : <p>{app.projectCategory} · {app.trade || "Trade not provided"} · Requested amount: ₹{app.requestedAmount?.toString() ?? "Not provided"}</p>}</div></details>
    <section className="panel space-y-4"><h2 className="text-xl font-bold">2. Scheme</h2><p>{app.loanScheme?.name ?? "No scheme selected"}</p>{draft && (schemes.length ? <AshaForm action={chooseAshaSchemeAction.bind(null, caseId)} label="Save scheme"><label className="block">Schemes meeting the checked requirements<select className="field mt-2" name="schemeId" required defaultValue={app.loanSchemeId ?? ""}><option value="" disabled>Choose a scheme</option>{schemes.map(scheme => <option key={scheme.id} value={scheme.id}>{scheme.name}</option>)}</select></label><p className="text-sm text-slate-600">Matching depends on the details entered. The officer still checks eligibility and documents.</p></AshaForm> : <p className="text-amber-800">No eligible match yet. Open Villager details and complete or correct the answers.</p>)}</section>
    <details className="panel" id="documents"><summary className="cursor-pointer font-bold">3. Documents · {app.documents.length} uploaded</summary><div className="mt-5 space-y-5"><p className="text-sm">Required by the selected scheme: {app.loanScheme?.requiredDocuments.join(", ") || "Choose a scheme to see its document list."}</p>{["DRAFT", "SUBMITTED"].includes(app.status) && <AshaForm action={uploadAshaDocumentAction.bind(null, caseId)} label="Upload document"><label className="block">Document type<select className="field mt-2" name="type" required>{Object.values(DocumentType).map(type => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label><label className="block">File (PDF or image, up to 5 MB)<input className="field mt-2" name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" required /></label></AshaForm>}{app.documents.map(doc => <article key={doc.id} className="rounded-xl border p-4"><p className="font-semibold">{doc.type.replaceAll("_", " ")} · {doc.status.replaceAll("_", " ")}</p><p className="text-sm break-all">{doc.originalFileName}</p>{doc.failureReason && <p className="mt-2 text-red-800">Officer feedback: {doc.failureReason}</p>}<form action={downloadAshaDocumentAction.bind(null, caseId, doc.id)}><button className="mt-2 text-sm underline">View file</button></form></article>)}{!app.documents.length && <p>No documents uploaded yet.</p>}<p className="text-xs text-slate-500">Uploading a file does not verify it. For changes after review starts, contact the reviewing officer.</p></div></details>
    {draft && app.loanScheme && <section className="panel space-y-4"><h2 className="text-xl font-bold">4. Submit for officer review</h2><p className="text-sm">Read the details back to the villager. This sends an assisted application to the officer; branch arrangements and document checks remain pending.</p><AshaForm action={submitAshaCaseAction.bind(null, caseId)} label="Submit for officer review"><label className="flex gap-3"><input type="checkbox" name="confirmation" value="yes" required /><span>I read back the details and the villager agreed to submit.</span></label></AshaForm></section>}
    <details className="panel"><summary className="cursor-pointer font-bold">Follow-up and review history</summary><div className="mt-5 space-y-5"><AshaForm action={saveAshaFollowUpAction.bind(null, caseId)} label="Save follow-up"><label className="block">Next follow-up date<input name="date" type="date" className="field mt-2" defaultValue={record.followUpAt ? new Date(record.followUpAt.getTime() + 19800000).toISOString().slice(0, 10) : ""} /></label><label className="block">My follow-up note<textarea name="note" className="field mt-2" maxLength={1000} defaultValue={record.followUpNote ?? ""} /></label><p className="text-xs">Leave the date blank to clear it. Notes stay in your workspace; contact the officer separately for correction requests.</p></AshaForm>{history.map(event => <div key={event.id} className="border-t pt-3"><p className="font-semibold">{event.toStatus.replaceAll("_", " ")} · {date(event.createdAt)}</p>{event.note && <p className="text-sm">{event.note}</p>}</div>)}</div></details>
  </div>;
}
